### ISSUE TITLE
Use the lineno package

### ISSUE THREAD

**Issue by davidweichiang** [acl-org/acl-pub#26]
The NeurIPS style file uses the lineno package to number actual lines instead of approximately like we do.

**Comment by mjpost** [comment]
This really nice. This produces nice output that is much less obtrusive to reviewers making margin notes:

```tex
\usepackage[switch,modulo]{lineno}
\linenumbers 
```

**Comment by davidweichiang** [comment]
The NeurIPS style does have to do some hacking to get equations to be numbered also, though.

**Comment by mjpost** [comment]
Per [this document](https://texblog.org/2012/02/08/adding-line-numbers-to-documents/), that can be done with

```latex
\usepackage[switch,displaymath,mathlines]{lineno}
\linenumbers
```

I have tried to get this to work by removing the current line numbering code and adding the following.

```latex
\ifaclfinal\else
  \usepackage[switch,displaymath,mathlines]{lineno}
  \linenumbers
\fi
```

Removing the current line numbering works, but the additional code above causes line numbers to always be printed, and I don't understand LaTeX well enough to know how to fix it.

One thought was that instead of having a macro `\aclfinalcopy`, we could implement it as a package-level option. I also think we should get rid of `\aclpaperid`—it never made sense to have to submit your paper twice, and if the IDs need to be added, it would be better to add stamping code to ACLPUB and ask Rich to run that in Softconf.

**Comment by mjpost** [comment]
I was able to figure this out. In lieu of the `\aclfinalcopy` macro, one now has to remove `blindcopy` from the ACL package options. I see that `\aclpaperid` had already been removed.

**Comment by davidweichiang** [comment]
Cool! But equation line numbering isn't working for me.
