### ISSUE TITLE
emnlp2018.sty interacts with subfig package

### ISSUE THREAD

**Issue by jeisner** [acl-org/acl-pub#8]
Captions were coming out as 11pt in one of my EMNLP 2018 submissions, instead of the prescribed 10pt, which looks nicer (easier to distinguish from body text) and takes up less space.

Figured out after deadline that the problem was  \usepackage{subfig}.  emnlp2018.sty does something magical to change captions from 11pt to 10pt, but subfig apparently turns the caption text (though not the "Figure 1:" part) back to 11pt.  

I don't know if there's anything to be done about this.  If emnlp2018 used the standard solution \usepackage[small]{caption}, maybe it would interact okay with subfig (I haven't checked).  But unfortunately small is 9pt in this document class (see https://tex.stackexchange.com/questions/24599/what-point-pt-font-size-are-large-etc), and there is no command for 10pt.  So I guess that's why some other magic was used.

**Comment by jeisner** [comment]
Thanks Stephanie - glad you were already aware of it.
(Yes, emnlp2018.sty is almost identical to naaclhlt2018.sty.)

**Comment by slukin** [comment]
I just tested this-- if you put the following directly into the .sty file, authors won't have to add anything to their .tex file. They can use the subcaption, caption, and subfigure packages without the font changing. 

\usepackage{caption}
\DeclareCaptionFont{10pt}{\fontsize{10pt}{12pt}\selectfont}
\captionsetup{font=10pt}

I don't know if there is a general preference for trying to not include more packages than necessary in the .sty file, but we had probably ~100 of our submission with this problem (and I asked each one to add the lines). Since so many used it, I'm in favor of just including the package in the .sty. I'm going to update the acl.sty for NAACL 2019 with this fix.

**Comment by davidweichiang** [comment]
I think this was fixed in 33c0d71d226001f5ef355391585b05b82a76df3a, right?
