### ISSUE TITLE
anthology xml format

### ISSUE THREAD

**Issue by danielgildea** [acl-org/acl-pub#9]
There are some mismatches between what the script [anthologize.pl](https://github.com/acl-org/acl-pub/blob/gh-pages/assets/files/create_book/bin/anthologize.pl) produces and what the script that reads these xml files, [xml_import.rake](https://github.com/acl-org/acl-anthology/blob/master/lib/tasks/xml_import.rake) expects.

1. The file produced is not valid xml, because the characters & < and > are not escaped,
and because accents are represented with HTML escape codes rather than xml escape codes (or plain UTF8, which would also be fine).  This makes it difficult to parse the file with standard libraries.  See issues https://github.com/acl-org/acl-anthology/issues/63 https://github.com/acl-org/acl-anthology/issues/74
The escape codes are produced by [db-to-html.pl](https://github.com/acl-org/acl-pub/blob/gh-pages/assets/files/create_book/bin/db-to-html.pl)

2. The names include fields `<von>` and `<jr>`, which are dropped on the floor by the
import script.  See issue https://github.com/acl-org/acl-anthology/issues/70

3. Finally, we have no mechanism for protecting capitalization in the paper titles
for words such as "English" and "LSTM".  Bibtex styles, including ACL's Bibtex styles,
typically render these words lower case unless they are protected by braces.  The [instructions for publication chairs](https://github.com/acl-org/acl-pub/blob/gh-pages/002.book.md) instruct them to insert braces.  The braces are stripped out by [db-to-html.pl](https://github.com/acl-org/acl-pub/blob/gh-pages/assets/files/create_book/bin/db-to-html.pl#L381) line 381.  Ideally, we should agree on a representation and maintain  this information on the anthology side.

**Comment by davidweichiang** [comment]
A few more issues I see:
- Italics are removed, but sometimes are important to the meaning of a paper title. Should they be preserved?
- Similarly for boldface and small caps, but there's less reason to preserve these.
- A bug in the handling of italics was fixed by https://github.com/acl-org/acl-pub/commit/2661d2d88e76c9e87be85e61ba190f8e9d93e0da, but it still won't handle `\emph{\'{e}}` correctly because of the internal curly braces.
- The rules for curly quotes could be improved: sometimes authors use straight single quotes like `'...'` and the current rules change that to `‘...‘`, which is not right.

I'll take a closer look later...

**Comment by davidweichiang** [comment]
There are a number of bugs in TeX::Encode:

- `\i`, `\"\i`, etc., are not converted to ı (used in Turkish names), ï, etc.
- `\dh` should be `ð` (used in Icelandic) but it becomes `ḥ`. It seems like `\dh` is being parsed as `\d h`, because `\da` gives an a with underdot, `\db` gives a b with underdot, etc.
- On the other hand, `{\d e}` should give an e with underdot, but doesn't.
- `%` is treated as a comment character, but in our data, `%` sometimes occurs unescaped in titles and abstracts. Similarly for an unpaired `$`.

Some bugs that are worked-around in anthologize.pl:

- Converts `---` to `–-` (en-dash followed by hyphen)
- Doesn't convert single or double quotes
- Doesn't convert `~` (non-breaking space)

Finally,

- Shouldn't the output file be opened with UTF-8 encoding? I don't understand how Perl does Unicode very well, but isn't the default behavior to look at environment variables like LANG to choose a default encoding?

**Comment by mjpost** [comment]
I think we should retain italics and small caps, since it's simple. As for bold face, I'm not sure. Do you know of any examples?

I think we should definitely be working in UTF-8. My understanding is that Perl reads LANG, but I also sometimes have to add `-C31` to the top of Perl scripts, or reopen STDIN and STDOUT in utf-8 mode. But I think we should start porting things to Python 3 where possible, so as to standardize on a single language. We should also start writing some test cases for some of these scripts...

**Comment by davidweichiang** [comment]
Small caps and boldface are both used a handful of times, and underlining once. All are used for the same purpose: highlighting the name of a system, or explaining its acronym, as in (**L**et's **I**nvent **S**ome **A**cronym).

(Boldface is also used in `\textbf{Invited Talk:} ...`, but I'm not worried about losing that.)

Italics is used much more and for more diverse purposes, like foreign words or emphasis.

**Comment by davidweichiang** [comment]
Does anyone happen to know how the multiple XML files (one per volume) generated by make_anthology.sh get merged into a single XML file as found in the Anthology?

**Comment by mjpost** [comment]
I haven’t handled this yet, but assume that they are just cut-and-pasted. The process I’ve seen starts with the separate volume bibs anyway.

**Comment by davidweichiang** [comment]
Oh, maybe that's why anthologize.pl appends to the output XML instead of rewriting it.

Another question: Does anyone happen to know why anthologize.pl wants to be told the volume number (e.g., 1) when it could be inferred from the URLs? (This option has only one correct value, or else the script does not work.)

**Comment by mjpost** [comment]
I don't know, having never run this, but [the call from make_proceedings.sh](https://github.com/acl-org/acl-pub/blob/gh-pages/assets/files/aclweb_proceedings/make_anthology.sh) seems to read in [an "acronyms" list](https://github.com/acl-org/acl-pub/blob/gh-pages/assets/files/aclweb_proceedings/acronyms_list.txt) where the volume ID (given in the third field) also seems to be redundant, though perhaps easier to specify manually than figuring out how to implement a hash counter in bash...

It occurs to me that @phikoehn might be able to shed some light on some of this (I think some of the scripts might originate from him).

**Comment by davidweichiang** [comment]
The current anthologize.pl looks for attachments in the proceedings.tgz from START and links them into the directory that is sent to the Anthology. But it doesn't add an `<attachment>` element to the XML. I can't find any code that does this. Does anyone know where it happens?

**Comment by mjpost** [comment]
I don't have any idea. Maybe @knmnyn does?

**Comment by davidweichiang** [comment]
This discussion parallels https://github.com/acl-org/acl-anthology/pull/150 (my fault) but doesn't really fit well in either. I'll create a new issue so this comment thread can be laid to rest!

**Comment by davidweichiang** [comment]
Continued from https://github.com/acl-org/acl-anthology/pull/150.

@slukin reports that starting with NAACL 2019, START will ask authors to categorize attachments as notes, software, or datasets. @slukin, do you know how they will appear in the proceedings.tgz that START generates? Does anthologize.pl need to be updated for it?

**Comment by davidweichiang** [comment]
I think the move to ACLPUB is done and the new scripts cover all the issues raised above.
